### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by SDNAFIO** [simonalexanderson/StyleGestures#1]
Hello,
can you provide a download link to the required training data?
Unfortunately, I can not find it.

Thank you

**Comment by ghenter** [comment]
Hi @SDNAFIO, and thank you for your interest in our work!

The gesture data is available at http://trinityspeechgesture.scss.tcd.ie/ . Trinity College Dublin require interested parties to sign a license agreement and receive approval before gaining access the material, so we cannot host it here.

The Edinburgh locomotion data and associated processing code can be obtained at https://bitbucket.org/jonathan-schwarz/edinburgh_locomotion_mocap_dataset . We are in contact with Edinburgh regarding sharing our small extension of that material (different frame rate and trajectory smoothing), but we do not yet know what the eventual decision will be.

Finally, the quadruped data is linked from GitHub at https://github.com/sebastianstarke/AI4Animation . A direct link to the data is http://www.starke-consult.de/UoE/GitHub/SIGGRAPH_2018/MotionCapture.zip , but please also see the associated content on GitHub for license information etc.

**Comment by SDNAFIO** [comment]
Thanks for the quick response!

I'm particularly interested in training with the locomotion dataset.
So to my understanding, the Edinburgh locomotion data, as it is available for download, is recorded with 60Hz, while you used a variation with 20Hz (according to  "framerate": 20 in locomotion.json).
Is it sufficient to adapt the framerate setting to 60Hz to obtain feasible results with the available dataset, or are some further changes needed?

**Comment by simonalexanderson** [comment]
Here is a link to our pre-processed version of the locomotion data. Please see the included README for details.

https://kth.box.com/s/quh3rwwl2hedwo32cdg1kq7pff04fjdf

**Comment by Svito-zar** [comment]
@SDNAFIO , has your question been answered?

**Comment by bigpo** [comment]
> Hello again,
> 
> The `framerate` setting only points to which dataset file to use. These files should be called "`all_locomotion_train_XXfps.npz`" and "`all_locomotion_test_XXfps.npz`" and reside in the data directory specified in the `locomotion.json` file (see `./motion/datasets/locomotion.py`). To get going, you can download the 60 fps Edinburgh datasets, rename them to `all_locomotion_txxxx_60fps.npz` and set the json framerate to 60 fps (or better up – resample the data to 20 fps and rename the files accordingly).
> 
> Aside from the difference in frame rate, we applied more smoothing the motion of the root node (on the floor underneath the character), to remove footfall cues such as periodicity in the root-node motion. This is optional, but we believe it makes MoGlow models generalise better. We also augmented the data with the locomotion trials from the CMU and HDM05 databases. To reproduce our processing, you need to download the data at http://theorangeduck.com/media/uploads/other_stuff/motionsynth_data.zip and modify the processing script called `export.py`. We 1) pooled data, 2) downsampled to 20 fps, and 3) applied smoothing with 5 frames on the trajectory position and 10 frames for the trajectory direction. See the MoGlow manuscript on arXiv at https://arxiv.org/abs/1905.06598 for more details.
> 
> Hope this helps!

hi @ghenter,  thanks for your detailed description here. I'm  little confused about the  `export.py`'s results.  It's have 73 dims feature per frame, but 66 dims you offered in  https://kth.box.com/s/quh3rwwl2hedwo32cdg1kq7pff04fjdf . Could you   tell me what am i missing or offer an preprocess script for the raw data? Thanks!

**Comment by simonalexanderson** [comment]
Hi,
The last features in the Holden et al. code are related to foot contacts and not needed for MoGlow. You should only use the joint positions and the 3 root motion features. If I’m not mistaking (I don’t have the code in front of me right now) that should sum up to 66. Hope this answers your question!

**Comment by bigpo** [comment]
> Hi,
> The last features in the Holden et al. code are related to foot contacts and not needed for MoGlow. You should only use the joint positions and the 3 root motion features. If I’m not mistaking (I don’t have the code in front of me right now) that should sum up to 66. Hope this answers your question!

it helps! thanks a lot.

**Comment by wangzheliu** [comment]
> 
> 
> > Hi,
> > The last features in the Holden et al. code are related to foot contacts and not needed for MoGlow. You should only use the joint positions and the 3 root motion features. If I’m not mistaking (I don’t have the code in front of me right now) that should sum up to 66. Hope this answers your question!
> 
> it helps! thanks a lot.

hi,Did you run this program successfully,I run the program,but show some wrong,

(moglow) [liu@no3@node02 StyleGestures]$ python train_moglow.py '/hparams/locomotion.json' locomotion
  File "train_moglow.py", line 49
    trainer = Trainer(**built, data=data, log_dir=log_dir, hparams=hparams)
                             ^
SyntaxError: invalid syntax
Do you meet same wrong?I use pytorch1.5,python3.7.thank you very much.

**Comment by jeff-rp** [comment]
Hi,
Did anyone successfully get access to [gesture data](http://trinityspeechgesture.scss.tcd.ie) ?
I submitted my request but they don't reply for a week...

**Comment by wangzheliu** [comment]
> 
> 
> Hi,
> Did anyone successfully get access to [gesture data](http://trinityspeechgesture.scss.tcd.ie) ?
> I submitted my request but they don't reply for a week...

me too

**Comment by simonalexanderson** [comment]
> > > Hi,
> > > The last features in the Holden et al. code are related to foot contacts and not needed for MoGlow. You should only use the joint positions and the 3 root motion features. If I’m not mistaking (I don’t have the code in front of me right now) that should sum up to 66. Hope this answers your question!
> > 
> > 
> > it helps! thanks a lot.
> 
> hi,Did you run this program successfully,I run the program,but show some wrong,
> 
> (moglow) [liu@no3@node02 StyleGestures]$ python train_moglow.py '/hparams/locomotion.json' locomotion
> File "train_moglow.py", line 49
> trainer = Trainer(**built, data=data, log_dir=log_dir, hparams=hparams)
> ^
> SyntaxError: invalid syntax
> Do you meet same wrong?I use pytorch1.5,python3.7.thank you very much.

Your path to the json file is incorrect, try ’hparms/locomotion.json’ (without leading ‘/’). Python 3.7 and pytorch 1.5 should be fine. Hope this helps.

**Comment by wangzheliu** [comment]
> 
> 
> > > > Hi,
> > > > The last features in the Holden et al. code are related to foot contacts and not needed for MoGlow. You should only use the joint positions and the 3 root motion features. If I’m not mistaking (I don’t have the code in front of me right now) that should sum up to 66. Hope this answers your question!
> > > 
> > > 
> > > it helps! thanks a lot.
> > 
> > 
> > hi,Did you run this program successfully,I run the program,but show some wrong,
> > (moglow) [liu@no3@node02 StyleGestures]$ python train_moglow.py '/hparams/locomotion.json' locomotion
> > File "train_moglow.py", line 49
> > trainer = Trainer(**built, data=data, log_dir=log_dir, hparams=hparams)
> > ^
> > SyntaxError: invalid syntax
> > Do you meet same wrong?I use pytorch1.5,python3.7.thank you very much.
> 
> Your path to the json file is incorrect, try ’hparms/locomotion.json’ (without leading ‘/’). Python 3.7 and pytorch 1.5 should be fine. Hope this helps.

(base) [liu@no3@node05 StyleGestures]$ python train_moglow.py 'hparams/locomotion.json' locomotion
  File "train_moglow.py", line 49
    trainer = Trainer(**built, data=data, log_dir=log_dir, hparams=hparams)
                             ^
SyntaxError: invalid syntax
I run the  program On your advice，but show same wrong,Do you have the same problem

**Comment by ghenter** [comment]
For the record, the run-time issues that @wangzheliu posted about in this thread are not related to the training data and were solved in a separate issue, issue #5. If you are having similar issues, look there first.

**Comment by pjyazdian** [comment]
> Hi,
> Did anyone successfully get access to [gesture data](http://trinityspeechgesture.scss.tcd.ie) ?
> I submitted my request but they don't reply for a week...

Hi,
Yes I did. I filled the request form and they provided a username and password. However, the dataset has missing part. Also, the moglow doesn't have pre-processing for the gesture dataset.
Is anyone able to provide some hints for preprocessing trinity?
Thanks!

**Comment by ghenter** [comment]
> the dataset has missing part

@pjyazdian, out of interest, what specific parts/aspects are you missing in the data? If you believe data was incorrectly omitted you may contact the dataset provider about that.

> moglow doesn't have pre-processing for the gesture dataset. Is anyone able to provide some hints for preprocessing trinity?

Regarding processing the Trinity gesture data, we are looking to provide preprocessing guidelines and code in the near future, but that will be some time after our team members are back from their summer holidays. Until then, you will find a description of what we view as the most important preprocessing steps in issue #2.

**Comment by simonalexanderson** [comment]
@pjyazdian Now the data processing and guidelines are available, please see the updated README. Let me know if something is unclear or you run into problems processing the data.

**Comment by yutao007** [comment]
hi guys ,who have datasets    The gesture data is available at http://trinityspeechgesture.scss.tcd.ie/.please give me one  thanks!!! 
 fisherman007@126.com

**Comment by ghenter** [comment]
Dear @yutao007,

The gesture dataset at the URL you provided is protected by a license agreement that restricts distribution. You may only obtain it by agreeing to that license agreement and downloading it from the Trinity Speech-Gesture Dataset site, and not via e-mail from third parties.

**Comment by yutao007** [comment]
thanks,i have register  ,but still not received

**Comment by ghenter** [comment]
I see. My understanding is that registrations are processed manually (and not by me/us/our university), so I cannot tell when you will be given access, but I hope it will be soon. Unfortunately, we cannot send the material to you since we don't have proof of you signing the agreement, nor do we have authorisation from the dataset creators to share the data with others.

**Comment by yutao007** [comment]
you are right .can you  send model to me , i just play  demo like youtobe

**Comment by yutao007** [comment]
sorry ,i just   say  when you can open litt;e  model you have trained  . wo  can  play demo .thanks again .

**Comment by ghenter** [comment]
Providing a pre-trained model is issue #4 in this repository. We are planning to package and upload such a model here in the near future, but it is not feasible to do that right now because of some imminent deadlines on our side.

**Comment by yutao007** [comment]
thanks again .hope it quickly.

**Comment by Svito-zar** [comment]
Trinity Speech-Gesture Dataset contains now also the [GENEA Challenge](https://genea-workshop.github.io/2020/#gesture-generation-challenge) data release, which has motions in BVH format.

I think this issue can be closed now.

**Comment by ghenter** [comment]
Yes, although we might want to update the readme slightly to reflect this (e.g., that the processed data is available in a specific subfolder on the TCD server) and also check that the code in the repo is actually compatible with the data as released (e.g., does not assume that the data is unprocessed).

**Comment by saeed1262** [comment]
Hi,

Is there a specific reason that you used joint positions instead of joint angles? I guess one reason could be the topology of joint angle space which might not be compatible with the current architecture.
Also, is this possible to have preprocessed data represented by joint angles?
Thanks

**Comment by ghenter** [comment]
Hi @saeed1262,

> Is there a specific reason that you used joint positions instead of joint angles? I guess one reason could be the topology of joint angle space which might not be compatible with the current architecture.

Good question. From my personal perspective and my possibly fallible recollection, I would say that the reasons for using joint angles were 1) that's what our starting dataset, [the Edinburgh Locomotion MOCAP Database](https://bitbucket.org/jonathan-schwarz/edinburgh_locomotion_mocap_dataset/src/master/) from [Habibie et al. (2017)](http://www.bmva.org/bmvc/2017/papers/paper119/paper119.pdf), and its associated processing code used, 2) the topological concerns you mention, and 3) inexperience on my part as to the importance of using joint angles in graphics applications, especially as we were targetting non-graphics conferences at first. However, it turns out that joint angles with an appropriate parameterisation work equally well, and that's what we used for [the gesture-generation paper at EUROGRAPHICS](https://diglib.eg.org/bitstream/handle/10.1111/cgf13946/v39i2pp487-496.pdf?sequence=1&isAllowed=y) and its corresponding code in this repo.

Within a month there will be a substantial update to [the MoGlow paper on arXiv](https://arxiv.org/abs/1905.06598) and its associated demonstration video on YouTube to present more experiments, including strong results on locomotion data parameterised using joint angles, without using any postprocessing of the raw output (in contrast to many existing motion-generation systems). The code will also be updated to match. Please e-mail us if you wish to read the revised paper before it becomes available on arXiv.

> Also, is this possible to have preprocessed data represented by joint angles?

The GENEA Challenge data that @Svito-zar mentioned in [a comment three days ago](https://github.com/simonalexanderson/StyleGestures/issues/1#issuecomment-689545497) is a preprocessed dataset of gesture motion represented by joint angles. It can be downloaded from a subfolder of the [Trinity Speech-Gesture Dataset server](https://trinityspeechgesture.scss.tcd.ie/) after signing their license agreement and receiving approval.

**Comment by simonalexanderson** [comment]
I can add that another reason for usíng joint positions was to assess model capabilities without the extra foot-sliding you get from angle errors propagating the hierarchy (small errors at the upper leg can cause the foot to move substantially).  But as Gustav mentioned above, our later experiments using joint angles did not show such problems.

**Comment by saeed1262** [comment]
Thanks for the detailed response, Gustav and Simon.

**Comment by saeed1262** [comment]
Hi. Can you explain how you preprocessed the quadruped data?

**Comment by evgenytumanov** [comment]
Hi. 
@simonalexanderson, I'm trying to replicate your results on Trinity data. I'm quite confused with audio-animation synchronization. Current data on https://trinityspeechgesture.scss.tcd.ie/ is located in four folders
BVH_from_clap/ , FBXs/  , FBXs_from_clap/ and Audio

I guess, that the right way to synchronize things is
Convert FBXs/ to BVHs/ somehow, and then use synchronize_trinity.py to synchronize the data. It was your pipeline I guess. Is it true?

Another way I guess to get pretty much the same is
Use BVH_from_clap/ and Audio/ . They look synchronized. But to get exactly the data you used I need to remove some scenes, namely 03, 09, 20 and a  few more, what's more, I need to cut some scenes according to information in offsets.csv. Is this statement true?

**Comment by ghenter** [comment]
Hi @evgenytumanov,

@simonalexanderson knows a lot more about the specifics of the data than I do, but my understanding is that the synchronisation in the original Trinity Speech-Gesture Dataset occasionally has problems. Personally, I would recommend that you train your system on the data from the GENEA Challenge instead. That data is a processed version of the original Trinity material, and was recently made available in the same repository and is covered by the same license agreement. The challenge dataset has been preprocessed to fix synchronisation issues and similar, and to create a canonical train and test split for the data (you will have to create your own dev set from the training portion, though).

To read more about the GENEA Challenge and its data, please [see our first paper made available on Zenodo](https://zenodo.org/record/4094697#.X4ml9FmxXUI), which we uploaded earlier today. Some colleagues and I are also arranging a workshop associated with the GENEA Challenge on Sunday (two days from now), and a major part of the workshop programme consists of presentations and discussions of different gesture-generation systems trained on the GENEA Challenge data. If you're interested, registration is open at no cost at [the GENEA Workshop 2020 website](https://genea-workshop.github.io/2020/).

**Comment by evgenytumanov** [comment]
@ghenter I'm looking at the GENEA data and cannot figure out why audio and corresponding motion file are not of the same length. Training data, Recording_001.wav is 12:02 long but the Recording_001.bvh is 11:58 long. Why?

**Comment by Svito-zar** [comment]
@evgenytumanov , sometimes length is different, but all the files are synchronized and t=0 is indeed always the same.

**Comment by evgenytumanov** [comment]
Ok, thank you, guys!

**Comment by saeed1262** [comment]
> Hi. Can you please explain how you preprocessed the quadruped data?

Hi. Any clue regarding this question?

**Comment by ghenter** [comment]
Unfortunately, I do not know the specifics of how the quadruped data was preprocessed. I think @simonalexanderson is the only person who can answer that.

**Comment by evgenytumanov** [comment]
Hi, guys, could you please tell which Speech 2 Text system was used for GENEA Challenge dataset?

**Comment by saeed1262** [comment]
Hi @ghenter  and @simonalexanderson ,
Do you have the list of samples extracted from CMU and HDM05 for locomotion data?

Thanks

**Comment by simonalexanderson** [comment]
Hi @saeed1262,
Here are the lists of the files we used for the evaluations, inculding the samples we used from the Edinburgh Locomotion Dataset. Note that the final MoGlow paper also has visualizations with skinned characters. For those we used the LAFAN1 and Kinematica datasets.

[train_files.txt](https://github.com/simonalexanderson/StyleGestures/files/5881136/train_files.txt)
[test_files.txt](https://github.com/simonalexanderson/StyleGestures/files/5881139/test_files.txt)

**Comment by saeed1262** [comment]
Thanks, @simonalexanderson!
That helps a lot.
Can I know why for the joint angles you used LAFAN1 instead of what you used for joint positions?

**Comment by simonalexanderson** [comment]
This was due to the higher data quality of LAFAN1 and Kinematica. Joint angle representations cause more footsliding than joint positions, as output errors sum up through the skeleton hierarchy. We found that the pooled LAFAN1 and Kinematica data caused less footsliding than the pooled CMU, HDM05 and Edinburgh data. Note that results in our videos were obtained without any post-processing steps s.a. foot stabilisation, which is quite common in other studies.

**Comment by saeed1262** [comment]
That makes sense. Thanks, @simonalexanderson!

**Comment by Svito-zar** [comment]
Can this issue be closed now?

**Comment by nefeliandreou** [comment]
Hi @ghenter and @simonalexanderson,

I am trying to reproduce the MoGLOW results using the _joint angle representation_. In the repo you mention that for this application you use data from the LAFAN1 and Kinematica datasets. Do you train the model using these datasets only? If so, can you provide details for the train/test splits? 

Thanks a lot!

**Comment by zf223669** [comment]
Hi, This link doesn't seem to be working:
https://kth.box.com/s/quh3rwwl2hedwo32cdg1kq7pff04fjdf
It showed that:
This shared file or folder link has been removed or is unavailable to you.

**Comment by ghenter** [comment]
Hi @zf223669,
Our university recently transitioned from using Box to Dropbox, invalidating all our data-sharing links.
Since I don't have a copy of the data myself, @simonalexanderson will have to create an updated link to the data.

**Comment by zf223669** [comment]
> Hi @zf223669, Our university recently transitioned from using Box to Dropbox, invalidating all our data-sharing links. Since I don't have a copy of the data myself, @simonalexanderson will have to create an updated link to the data.

Thank you!

**Comment by ghenter** [comment]
@zf223669 Here's the updated link to the dataset, shared via OneDrive:
https://kth-my.sharepoint.com/:f:/g/personal/simonal_ug_kth_se/EuzCqSiScf5EvwWgZJ8EZ3wB24oPsKca9klzGzxzV-4N6g?e=BG1ELf
Simon will also update the readme shortly.

**Comment by NoGameNoLive** [comment]
Hellow, the newest dataset link does not seem to work.  
It showed that: 
Länken har upphört att gälla.

**Comment by NoGameNoLive** [comment]
> @NoGameNoLive不幸的是（令人讨厌的是），大学政策要求来自新数据共享（OneDrive）的所有链接最多在180天后过期。这就是现在这里发生的情况。
> 
> @simonalexanderson必须创建一个新链接并将其添加到自述文件中。遗憾的是，由于他目前的日程安排很忙，这种情况要到下周才可能发生。从长远来看，我们将不得不寻找另一种解决方案，例如芝诺多。

Thank you!

**Comment by NoGameNoLive** [comment]
Hi, when running prepare_locomotion_dataset.py what is the held out file? is that from CMU or HDM05 and just rename it? or I need reconstruct a bvh？

**Comment by zixuan1208** [comment]
Hi, the link of the processed version of the Trinity Speech-Gesture Dataset can not access.
It showed that:
The requested URL was not found on this server.

**Comment by simonalexanderson** [comment]
Now the link is working again. Here it is for reference:
https://kth-my.sharepoint.com/:f:/g/personal/simonal_ug_kth_se/Ejv1XNdMwm1NpXCUGNUKjisBY2q98WfcRd2NKbAuKrOAIg?e=oOcMtb
