### ISSUE TITLE
where is the data_pipe.sav file?

### ISSUE THREAD

**Issue by piaohai** [simonalexanderson/StyleGestures#12]
hello, when i run   command python prepare_datasets.py , it's seem  not work, cand not find sav file?  so how to resolve it ? tks.

python prepare_datasets.py 
['NaturalTalking_04.bvh', 'NaturalTalking_11.bvh', 'NaturalTalking_23.bvh', 'NaturalTalking_05.bvh', 'NaturalTalking_19.bvh', 'NaturalTalking_15.bvh', 'NaturalTalking_08.bvh', 'NaturalTalking_01.bvh', 'NaturalTalking_07.bvh', 'NaturalTalking_18.bvh', 'NaturalTalking_22.bvh', 'NaturalTalking_16.bvh', 'NaturalTalking_26.bvh', 'NaturalTalking_30.bvh', 'NaturalTalking_27.bvh', 'NaturalTalking_12.bvh', 'NaturalTalking_14.bvh', 'NaturalTalking_02.bvh', 'NaturalTalking_25.bvh', 'NaturalTalking_10.bvh', 'NaturalTalking_17.bvh', 'NaturalTalking_13.bvh', 'NaturalTalking_21.bvh']
Found speech features. skipping processing...
Found motion features. skipping processing...
Traceback (most recent call last):
  File "prepare_datasets.py", line 215, in <module>
    copyfile(os.path.join(motion_path, 'data_pipe.sav'), os.path.join(processed_dir,f'data_pipe_{fps}fps.sav'))
  File "/home/user/miniconda2/envs/py383/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../data/trinity/processed/features_20fps/joint_rot/data_pipe.sav'

**Comment by piaohai** [comment]
ok, it was done

**Comment by guofengming11-chinese** [comment]
> ok, it was done

Hello, I have the same problem, how to resolve it ,thanks !

**Comment by nagyrajmund** [comment]
@guofengming11 This problem can happen if `prepare_datasets.py` is interrupted, then run again. Deleting the `processed/joint_rot` data directory should solve it.
