### ISSUE TITLE
maybe there are some bugs in latest update

### ISSUE THREAD

**Issue by txjlx** [simonalexanderson/StyleGestures#20]
Hi,   thanks for your great work.
I tracked your latest update and faced some problems, maybe they were bugs or my mistake: 
1.  line 42 in train_moglow.py: data=dataset(hparams, is_training), is_training cannot pass to class Datasets
2.  line 43 in train_moglow.py: data has no attribute 'n_channels', maybe it's data.get_train_dataset().n_channels()
3.  line 46 in train_moglow.py: built = build...  in which 'hparams' has no attribute 'Glow.distribution'. And I checked the json file, there is no key named 'distribution' in 'Glow'.
After fixing these problems, it worked.

**Comment by simonalexanderson** [comment]
Thanks @txjlx for pointing this out. I have now updated the code.
