### ISSUE TITLE
Training time and GPU spec

### ISSUE THREAD

**Issue by riven314** [simonalexanderson/StyleGestures#3]
thanks for the amazing work!
What GPU model and how many GPU did you use for your training? And how long did it take?

**Comment by ghenter** [comment]
Thanks for the kind words, Alex. :)
The models in our paper were trained between 16 and 38 hours on a single Nvidia GeForce RTX 2080 Ti GPU. You can find more details in Table 1 in [the paper](https://diglib.eg.org/bitstream/handle/10.1111/cgf13946/v39i2pp487-496.pdf?sequence=1&isAllowed=y).
