### ISSUE TITLE
Strange results when I train with multiple GPUs.

### ISSUE THREAD

**Issue by flyingfish007** [simonalexanderson/StyleGestures#30]
Hi, 
Thank you very much for open source your code. I can get reasonable results when I train with the single gpu. But when I use multiple gpus to train the model with exactly same data and batch size, the results I get is very jittering. Just like a fast forward playing mode. Do you happen to know this issue? Does that mean your training code doesn't support multiple gpu for training ? 

Thank

**Comment by ghenter** [comment]
This is a known issue with [the Glow codebase we based our implementation on](https://github.com/chaiyujin/glow-pytorch/). Please see the text marked "Important note" in [our readme file](https://github.com/simonalexanderson/StyleGestures#readme):
> **Important note:** Although the code allows multi-GPU training, this is not supported as it leads to incorrect results.
