### ISSUE TITLE
Difference between time_steps and seqlen?

### ISSUE THREAD

**Issue by athn-nik** [simonalexanderson/StyleGestures#32]
Hey and thanks in advance for the help!
What is the difference betweern timesteps and seqlen in this function?
https://github.com/simonalexanderson/StyleGestures/blob/a7599355a7b6578dba96e5ec76cc7cfeedd272e8/motion/datasets/motion_data.py#L58
Based on the calls:
https://github.com/simonalexanderson/StyleGestures/blob/a7599355a7b6578dba96e5ec76cc7cfeedd272e8/motion/datasets/motion_data.py#L27
https://github.com/simonalexanderson/StyleGestures/blob/a7599355a7b6578dba96e5ec76cc7cfeedd272e8/motion/datasets/motion_data.py#L30
I cannot infer how it distinguishes semantically one from another..and how they also differ from n_frames. Should those all be equal? if not what should they be?
I also think that the call to `concat_sequence` on the motion_data(not the control or autoregressive) leaves the data "untouched". Is that supposed to happen?
Thanks!

**Comment by nagyrajmund** [comment]
Hi,

I'm not the author of the repository, but my understanding is that the `concat_sequence` function takes a number of short (e.g. 10 second) data segments, and returns all `seqlen` long windows in these segments concatenated to each other.

For example, if 
```python
data = np.array([ 
    # first segment
    [0, 1, 2, 3, 4], 
    # second segment
    [5, 6, 7, 8] 
])
# window length
seqlen = 3
```
then `self.concat_sequence(seqlen, data)` will return an array like this:
```python
np.array([ 
    # first window from both segments
    [ [0,1,2] , [5,6,7] ],
    # second window from both segments
    [ [1,2,3], [6,7,8] ],
    # third window from both segments
    [ [2,3,4], [7,8,9] ]
])
```

**Comment by nagyrajmund** [comment]
Hi,

I'm not the author of the repository, but my understanding is that the `concat_sequence` function takes a number of short (e.g. 10 second) data segments, and returns all `seqlen` long windows in these segments concatenated to each other.

For example, if
```python
data = [ 
    # first segment
    [frame_0, frame_1, frame_2, frame_3, frame_4], 
    # second segment
    [frame_5, frame_6, frame_7, frame_8, frame_9] 
]
# window length
seqlen = 3
```
then `self.concat_sequence(seqlen, data)` will return something like this:
```python
[ 
    # first window from both segments
    [ [frame_0, frame_1,2] , [frame_5, frame_6, frame_7] ],
    # second window from both segments
    [ [frame_1, frame_2,3], [frame_6, frame_7, frame_8] ],
    # third window from both segments
    [ [frame_2, frame_3, frame_4], [frame_7, frame_8, frame_9] ]
]
```

> What is the difference betweern timesteps and seqlen in this function?
In the above example, `timesteps` is 5 and `seqlen` is 3.

**Comment by ghenter** [comment]
Closing this issue, since it appears that the question has been answered.
