### ISSUE TITLE
For the freshmen about Gesture Generation

### ISSUE THREAD

**Issue by zf223669** [simonalexanderson/StyleGestures#35]
Hello Simon Alexanderson:
I am glad to communicate with you! I come from Communication University of Zhejiang, China.
I am quite interested in the research in the field of gesture generation for virtual Human , but I just started to set foot in this field. 
Could you please tell me what materials ,papers ,journal or books you can recommend to help me get started? 

Thank you !
Best,
ZhangFan

**Comment by ghenter** [comment]
This question has been addressed in another forum and I believe this issue should be closed.

**Comment by chuangyu-robotics** [comment]
see the workshop GENEA at first https://genea-workshop.github.io/2021/
