### ISSUE TITLE
About the Cuda version

### ISSUE THREAD

**Issue by zf223669** [simonalexanderson/StyleGestures#38]
Hi, I have set up the environment and run the project, however, the default cuda version in the style_gestures.json is 7.
I intent to switch the version to 10.2 or 11.3, but, after i change the setting in the json, like this cuda=11.3, it showed an error ,which show below:
ValueError: invalid literal for int() with base 10
And i change the 11.3 to 11 in json, it showed that:
Failed to find any valid gpu in ['cuda:11'], use `cpu`.

What`s that bug?
Thank you!

**Comment by zf223669** [comment]
@simonalexanderson

**Comment by ghenter** [comment]
@zf223669 Has your question in this issue been answered?
If so, I would recommend that you close the issue.

**Comment by ghenter** [comment]
Closing this since the question appears to have been answered.
