### ISSUE TITLE
About the swapaxes for self.x and self.cond

### ISSUE THREAD

**Issue by zf223669** [simonalexanderson/StyleGestures#39]
Dear sir:
    I`m reading your code about the StyleGestures, i met a problem with the code in motion_data.py, 
I could not understand why need to swap the self.x and sefl.cond`s axes:
     self.x = np.swapaxes(self.x, 1, 2)
     self.cond = np.swapaxes(self.cond, 1, 2)
I thought that the shape of the x and cond is [batch, seqLength, features]  before swap, why need to swap the seqLength and features?
as i know the LSTM`s default order is [seqLength, batch, features].
Could you explain more detail to me?

**Comment by zf223669** [comment]
@simonalexanderson 
Dear sir:
Im reading your code about the StyleGestures, i met a problem with the code in motion_data.py, I could not understand why need to swap the self.x and sefl.conds axes:
self.x = np.swapaxes(self.x, 1, 2)
self.cond = np.swapaxes(self.cond, 1, 2)
I thought that the shape of the x and cond is [batch, seqLength, features] before swap, why need to swap the seqLength and features?
as i know the LSTM`s default order is [seqLength, batch, features].
Could you explain more detail to me?

**Comment by ghenter** [comment]
I am sorry, but this code was written by @simonalexanderson, and I do not know enough about it to answer your question. I hope Simon can find the time to get back to you.

Did you check issue #26, which also concerns shape and LSTMs?

**Comment by simonalexanderson** [comment]
Hi @zf223669, and thank you for your observation. These swaps arise from my starting point using an image Glow implementation with dimensions (batch, channels, height, width). For time series data this translated to (batch, features, sequence, None), and thereby the swap from the more standard order (batch, sequence, features). For the LSTM there is a swap back to (batch, features, sequence) and the “batch first” flag is set.

You can of course organize the data in a nicer way by removing both these swaps, but then you need to change dimensions in the other flow transformations. Hope this answered your question.

**Comment by zf223669** [comment]
@simonalexanderson ok, thank you for your response.

**Comment by ghenter** [comment]
@zf223669 Has your question in this issue been answered?
If so, I would recommend that you close the issue.

**Comment by ghenter** [comment]
Closing this since all questions appear to have been answered.
