### ISSUE TITLE
Excuse me, where can I find the dataset used by Example3 in readme?

### ISSUE THREAD

**Issue by stormlooming** [simonalexanderson/StyleGestures#42]

**Comment by ghenter** [comment]
[The Trinity Speech-Gesture Dataset can be found here](http://trinityspeechgesture.scss.tcd.ie/).

You are required to sign a license agreement and be approved by the dataset owners before you can access the data. Part of that license agreement involves a "no distribution" clause:

> The Dataset and the license herein granted shall not be copied, shared, distributed, re-sold, offered for re-sale, transferred or sub-licensed in whole or in part except that you may make one copy for archive purposes only.

This clause means that no one who has access to the data is allowed to share it with you, except for Trinity College Dublin, who created the data. In particular, I cannot share it with you directly, as the readme states.

Does this answer your question?

**Comment by stormlooming** [comment]
> 

Thank you very much for your timely reply. I have got this and data set, but I don't know the specific steps. Which files do I need and what do I need to do with them? In other words, what do I need to do before I run Example3?

**Comment by ghenter** [comment]
You will need the files in the GENEA Challenge 2022 subfolder of the gesture dataset. That's the version of the data that this repository has been designed to run on. The readme then says:
> Place the data in the 'data/GENEA/source' folder and then run `python prepare_gesture_datasets.py` from the 'data_processing' folder.

If this is not sufficient to help you make progress, I will not be able to advise you much further, I'm afraid. I'm an expert on the machine learning, but not on the code or the data processing. @simonalexanderson could perhaps answer additional questions on the specific setup, but he is busy with a paper deadline and unlikely to have time to respond.

**Comment by stormlooming** [comment]
OK, I see. Thank you very much

**Comment by stormlooming** [comment]
I wonder if running Example3 is necessarily related to running example1 and 2? Are you going to run 1 and 2 before running 3?

**Comment by zf223669** [comment]
@ghenter 
Dear sir:
Im reading the code about the StyleGestures, i met a problem with the code in motion_data.py, I could not understand why need to swap the self.x and sefl.conds axes:
self.x = np.swapaxes(self.x, 1, 2)
self.cond = np.swapaxes(self.cond, 1, 2)
I thought that the shape of the x and cond is [batch, seqLength, features] before swap, why need to swap the seqLength and features?
as i know the LSTM`s default order is [seqLength, batch, features].
Could you explain more detail to me?

**Comment by ghenter** [comment]
Dear @zf223669,

I know that it might be frustrating not to receive a response on your earlier requests. I would have given your posts a response earlier if I knew the answer, but I didn't answer since I simply don't know the code that you are asking about. Please see my other post in issue #39 that you posted.

That said, let us keep this GitHub repository to one topic per issue. Please do not make responses to threads that are unrelated to the other posts in the thread, especially not when there already is a separate issue posted about the topic you are posting about. Spreading your posts across multiple issues to gain attention is considered bad netiquette, since it makes the GitHub issues more difficult to navigate for everyone else.

**Comment by zf223669** [comment]
Hi，The dataset could be found below:
https://trinityspeechgesture.scss.tcd.ie/

**Comment by ghenter** [comment]
> Hi，The dataset could be found below: https://trinityspeechgesture.scss.tcd.ie/

I linked to that dataset in [the first response in this thread](https://github.com/simonalexanderson/StyleGestures/issues/42#issuecomment-1123387919).

**Comment by ghenter** [comment]
> I wonder if running Example3 is necessarily related to running example1 and 2? Are you going to run 1 and 2 before running 3?

I'm not the coder, but I really believe that example 3 stands on it own, and can be run without having run either of examples 1 and 2 first.

I hope this answers your question, @stormlooming.

**Comment by ghenter** [comment]
Closing this since all questions appear to have been answered.
