### ISSUE TITLE
About the dataset 

### ISSUE THREAD

**Issue by KVBK01** [simonalexanderson/StyleGestures#47]
It seems that the updated link in readme has again expired...
It would be very helpful if you could again update the download link!

Thanks!

**Comment by simonalexanderson** [comment]
Thanks for noticing, it should be working now! 

It's very annoying, KTH shared folders expire after 6 months, so I need to update frequently...

**Comment by Chenmo1212** [comment]
Sorry, it sems that the link in readme has agin expired
