### ISSUE TITLE
What is the specific version of environment，such as pytorch ，python

### ISSUE THREAD

**Issue by wangzheliu** [simonalexanderson/StyleGestures#5]
I run    (moglow) [liu@no3@node02 StyleGestures]$ python train_moglow.py '/home/liu@no3/StyleGestures/hparams/locomotion.json' locomotion
  File "train_moglow.py", line 49
    trainer = Trainer(**built, data=data, log_dir=log_dir, hparams=hparams)
                             ^
SyntaxError: invalid syntax
what was wrong？
thanks a lot。

I use pytorch1.5，python3.7

**Comment by simonalexanderson** [comment]
pytorch1.5 and python3.7 should be fine. My guess is that the problem is due to invalid path.

**Comment by wangzheliu** [comment]
> 
> 
> pytorch1.5 and python3.7 should be fine. My guess is that the problem is due to invalid path.

base) [liu@no3@node05 StyleGestures]$ python train_moglow.py 'hparams/locomotion.json' locomotion
File "train_moglow.py", line 49
trainer = Trainer(**built, data=data, log_dir=log_dir, hparams=hparams)
^
SyntaxError: invalid syntax
I run the program On your advice，but show same wrong,Do you have the same problem

**Comment by simonalexanderson** [comment]
Double check that you are in the right conda environment. It looks you are running in the base env, and if you installed with the ‘environment.yml’ file, the env should be named ‘moglow’.

**Comment by wangzheliu** [comment]
> 
> 
> Double check that you are in the right conda environment. It looks you are running in the base env, and if you installed with the ‘environment.yml’ file, the env should be named ‘moglow’.

think you ，I install the environment again,the quesion is solved.
