### ISSUE TITLE
how to convert results to BVH format?

### ISSUE THREAD

**Issue by bigpo** [simonalexanderson/StyleGestures#8]
Hi,
Thanks for your nice work. The network's output is world positions about joints, I'm wondering is there a way to convert to BVH format? Because rotation info is quite useful for some applications. Thanks!

**Comment by ghenter** [comment]
Hi @bigpo and thanks for the compliment,

My understanding is that the output type differs between different networks in the repository: locomotion networks generate (Cartesian) joint positions, whereas the gesture network generates joint rotations as input. At least that is the case in our papers.

As you may know, joint rotations can always be converted to joint positions given skeleton information (bone lengths etc.), but the transformation is lossy and thus not invertible; we cannot easily convert joint positions to joint rotations. My impression is that BHV stores joint rotations and not joint positions, meaning that the locomotion output positions cannot easily be converted to BVH, but the output of the gesture models can. (There are some ways around this that involve inverse kinematics, which you can [read more about in this comment I made on reddit](https://www.reddit.com/r/MachineLearning/comments/hpv0wm/r_stylecontrollable_speechdriven_gesture/fxzb241/).)

I believe that the plan is to endow locomotion generation with joint-rotation information in the near future, but I this is not 100% certain. In the meantime, feel free to do a pull request or similar if you decide to go ahead and implement any functionality towards this end yourself. :)

**Comment by bigpo** [comment]
hi @ghenter ,  thanks for showing me the direction, i'll give it a try.
